[ADD] Product -  카테고리별, 베스트상품, Query Parameter를 사용한 filtering 기능
wecode-bootcamp-korea/39-1st-HealthEat-backend pull request #4
Opened 2022-11-20 13:51 UTC by Sangwon-cho

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- products 관련 요청들 처리
   - 카테고리별 제품 보내주기
   - 판매량에 따른 베스트 6 제품 보내주기
   - Query Parameter를 사용한 filter 기능 구현(brand,price range)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카테고리별
   - /products/category/:categoryId 의 url를 사용 -> categories의 테이블을 join으로 product 테이블과 연결시킨 후에 url로 받은 categoryId를 sql의 변수로 사용하여 클라이언트 요청대로 구별하여 데이터 제공
2. 베스트 6 
   - /products/best 의 url 사용 -> 기존 DB에 저장된 stock의 데이터를 기반으로 상위 6개의 제품 선택(ORDRY BY stock으로 정렬을 한후 limit 6를 사용해 상위 6개 선택)
3. Query Parameter
   - /products -> 다른 조건을 걸지 않았을때는 제품 전체의 데이터를 가져옴
   - /products?minPrice=10000&maxPrice=20000&brand=1&brand=3. -> 가격범위를 정한 후 조건들이 추가될 수 있게 brand의 조건을 "OR"로 받을 수 있게 구현. 각각 조건들이 정해지면 조건들을 AND로 묶어 해당 sql문에 조건으로 사용 
   - productQueryBuilderbrand.js를 사용하여 url의 정보를 받아와 해당 정보에 따른 filtering기능 구현 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 하나의 url을 사용해서 제품의 filtering을 구현하기위해 해당 조건에 맞춰 sub-query문을 작성하거나 또는 application JOIN을 사용할 수 있음을 알게되었습니다. 이번에는 sub-query를 사용하지 못했지만 그래도 기능대로 작동시키기 위해 거의 이틀을 고민하고 수정하였습니다. 
- url로 받아온 객체형태의 정보를 Object.entries라는 method를 사용하여 배열화를 하고 그내용을 map() 함수를 통과시켜 하나씩 원하는 형태의 데이터로 정리할 수 있다는 것이 정말 신기했습니다 
```
 const makeProductQueryBuilders = (params) => {
  const builderSet = {
    minPrice: minPriceFilterBuilder,
    maxPrice: maxPriceFilterBuilder,
    brand: brandFilterBuilder,
  };

  const whereClauses = Object.entries(params).map(([key, value]) =>
    builderSet[key](value)
  );
```

<br />

## :: 기타 질문 및 특이 사항
- 에러핸들링 관련해서는 월요일에 추가해서 올리도록 하겠습니다

2022-11-22 01:11 UTC, Kang-kyunghun requested changes

2022-11-22 01:11 UTC, Kang-kyunghun commented on src/util/productQueryBuilder.js
> +};
- 해당 함수를 만들었는데, 왜 best만을 ordering하는 api가 따로 있을까요?? 해당 함수를 어떻게 활용할 수 있을지 생각해 보세요.
- 변수 이름인 해당 변수가 어떤 데이터를 가지고 있는지 명확해야 합니다. obj라고 하면 오브젝트늘 나타낼 뿐인데, 해당 코드는 어디서 그냥 가져 왔다고 볼 수 밖에 없는 것 같네요. 
- 불필요한 콘솔은 지워 주세요.

2022-11-22 01:11 UTC, Kang-kyunghun commented on src/services/productService.js
> +} = require("../util/productQueryBuilder");
빌더 사용은 서비스가 아닌 모델에서 활용해 주세요.

2022-11-22 01:11 UTC, Kang-kyunghun commented on src/util/productQueryBuilder.js
> +  console.log(whereClauses);
콘솔 제거

2022-11-22 01:11 UTC, Kang-kyunghun commented on src/services/productService.js
> +};
하나의 API로 만들어 주세요.

2022-11-22 13:35 UTC, Sangwon-cho commented
리뷰 감사합니다. 말씀하신 것들 반영하여 올립니다.

2022-11-23 01:00 UTC, Kang-kyunghun requested changes

2022-11-23 01:00 UTC, Kang-kyunghun commented on src/services/productService.js
> +    ...filterOptions
filterOption이 어디서 온건지 안 보이네요??

설명 한 번 부탁드립니다.

2022-11-23 01:02 UTC, Kang-kyunghun commented
통신 결과 한 번만 올려주세요.

2022-11-23 01:02 UTC, merged